### ISSUE TITLE
Error on running in Anki 2.1.19

### ISSUE THREAD

**Issue by p2635** [barkdoll/daijirin-scraper#1]
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.19 (3c8690ae) Python 3.8.1 Qt 5.14.0 PyQt 5.13.2
Platform: Linux
Flags: frz=True ao=True sv=?
Add-ons possibly involved: Daijirin Dictionary Scraper

/home/seru/.local/share/Anki2/addons21/311119199/jisho_scraper.py:238: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if query is '':

**Comment by barkdoll** [comment]
@p2635 just saw this. Will look into it soon. Thanks for posting.
